# Generated by Django 5.1.4 on 2024-12-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_serviceproviderprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='service_types',
            field=models.ManyToManyField(related_name='breakdown_requests', to='myapp.servicetype'),
        ),
    ]
