# Generated by Django 5.1.4 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
