# Generated by Django 5.1.4 on 2024-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownrequest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
