# Generated by Django 5.1.4 on 2024-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_breakdownrequest_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='estimated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
