# Generated by Django 5.1.4 on 2024-12-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_breakdownrequest_estimated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
