# Generated by Django 5.1.4 on 2024-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_serviceproviderprofile_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='breakdownrequest',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
